# Generated by Django 5.0.6 on 2024-05-15 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime.now)),
                ('CreatedName', models.CharField(max_length=100)),
                ('SlugLink', models.SlugField(max_length=200)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
