# Generated by Django 5.0.6 on 2024-05-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_quotefrom_blog_quotetitle_blog_quotedname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Body',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
