# Generated by Django 5.0.6 on 2024-05-15 07:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='BodyTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
