# Generated by Django 5.0.6 on 2024-05-15 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_blog_tags_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
