# Generated by Django 5.0.6 on 2024-07-08 12:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact_form_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=500)),
                ('CreatedAt', models.DateField()),
                ('CreatedName', models.CharField(max_length=100)),
                ('BodyTitle', models.CharField(max_length=200, null=True)),
                ('Body', ckeditor.fields.RichTextField()),
                ('QuoteTitle', models.CharField(max_length=500, null=True)),
                ('QuotedName', models.CharField(max_length=100, null=True)),
                ('QuoteFrom', models.CharField(max_length=50, null=True)),
                ('SlugLink', models.SlugField(max_length=200)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
