# Generated by Django 5.0.6 on 2024-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=500),
        ),
    ]
