# Generated by Django 5.0.6 on 2024-07-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='QuoteFrom',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='QuoteTitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='QuotedName',
        ),
    ]
