# Generated by Django 5.0.6 on 2024-07-08 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_blog_quotefrom_remove_blog_quotetitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
