# Generated by Django 5.1.4 on 2025-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='invite_email',
            field=models.EmailField(max_length=254),
        ),
    ]
