# Generated by Django 5.0.6 on 2024-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='QuoteFrom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='QuoteTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='QuotedName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
