# Generated by Django 5.0.6 on 2024-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_bodytitle_alter_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Tags',
        ),
        migrations.AlterField(
            model_name='blog',
            name='CreatedAt',
            field=models.DateField(),
        ),
    ]
